Flower/Flower/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings



urlpatterns = [
    path('admin', auth_views.LoginView.as_view(template_name='adminControl/adminlogin.html'), name='admin'),
    # path('admin/', admin.site.urls),
    path('', include('Fulbari.urls')),
    path('', include('Product.urls')),
    # path('/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Flower/Product/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    name=models.CharField(max_length=40)
    product_image= models.ImageField(upload_to='product_image/',null=True,blank=True)
    price = models.PositiveIntegerField()
    description=models.CharField(max_length=40)
    def __str__(self):
        return self.name

    class Meta:
        db_table='product_tbl'



class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    is_active = models.BooleanField(default=True)




class Orders(models.Model):
    STATUS = (
        ('Ordered', 'Ordered'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=STATUS, default='Ordered')
    order_date = models.DateField(auto_now_add=True)

Flower/templates/adminControl/addproduct.html
{% extends 'admin_base.html' %}

{% block content %}


{% load static %}


<head>
  <style media="screen">
    a:link {
      text-decoration: none;
    }

    .note {
      text-align: center;
      height: 80px;
      background: -webkit-linear-gradient(left, #0072ff, #8811c5);
      color: #fff;
      font-weight: bold;
      line-height: 80px;
    }

    .form-content {
      padding: 5%;
      border: 1px solid #ced4da;
      margin-bottom: 2%;
    }

    .form-control {
      border-radius: 1.5rem;
    }

    .btnSubmit {
      border: none;
      border-radius: 1.5rem;
      padding: 1%;
      width: 20%;
      cursor: pointer;
      background: #0062cc;
      color: #fff;
    }

    .menu {
      top: 50px;
    }
  </style>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<br><br><br><br><br><br>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container register-form">
    <div class="form">
      <div class="note">
        <p>Add Products</p>
      </div>
      <div class="form-content">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="col-md-4 control-label" for="">PRODUCT NAME</label>
              <div class="col-md-12">
                <input name="name" placeholder="" class="form-control input-md" required="" type="text">

              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="">PRODUCT Price</label>
              <div class="col-md-12">
                <input name="price" placeholder="" class="form-control input-md" required="" type="number">

              </div>
            </div>

          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <label for="id_product_image">Product image:</label>
            <div class="col-md-4">
              <input type="file" name="product_image" accept="image/*" id="id_product_image">

            </div>
          </div>

        </div>
        <div class="form-group">
          <label class="col-md-4 control-label" for="">PRODUCT Description</label>
          <div class="col-md-12">

            <textarea name="description" placeholder="" class="form-control input-md" required=""
              type="text"> </textarea>

          </div>

        </div>
      </div>
    </div>
    <button type="submit" class="btnSubmit"> ADD</button>
  </div>
  </div>
  </div>
</form>

{% endblock %}

Flower/templates/adminControl/addtocart.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buy Now</title>
</head>
<body  >


    <h1>Floral Product</h1>
    <div class="content" style="background-image: url(//static/images/sale.jpeg);" >
    <section>
      <div class="register-wrapper">
      <div class="register-block">
      <h3 class="register-title">Buy Now</h3>
        <p>Please check the correct details to buy your products</p>
        <form action="/addtocart/{{productss.product_id}}" method="POST">


          {% csrf_token %}

        
        <label for="fname">Product Id</label><br>
        <input type="text" name="product_name" value="{{productss.product_id}}" placeholder="Prodct Name"/>

        <label for="fname">Your Name</label><br>
        <input type="text" name="your_name" placeholder="Your Name"/>

        <label for="fname">Email_Address</label><br>
        <input type="text" name="address" placeholder="Prodct Name"/>

        <label for="fname">Phone Number</label><br>
        <input type="text" name="phone_number" placeholder="Prodct Name"/>

        <label for="fname">Date</label><br>
        <input type="date" name="date" placeholder="Prodct Name"/>

        <label for="fname">Location</label><br>
        <input type="text" name="location" placeholder="Prodct Name"/>




    

              <input type="submit" value="Submit"/>
  
        </form>
      </div>
      </div>
    </section>
  </div>

</form>



</body>
</html>
{% endblock %}

Flower/templates/adminControl/admin_product.html
{% extends 'admin_base.html' %}
{% load static %}
{% block content %}


<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }

    .float{
	position:fixed;
	width:70px;
	height:70px;
	bottom:60px;
	right:60px;
	background-color:red;
	color:#FFF;
	border-radius:50px;
	text-align:center;
	box-shadow: 3px 3px 3px #999;
}

.my-float{
	margin-top:22px;
}
  </style>
</head>


<div class="container">
  <div class=""  style="background-color: azure;">
    <div class="panel-heading">
      <h6 class="panel-title">Total Product List</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr style="background-color: paleturquoise;">
          <th>Name</th>
          <th>Image</th>
          <th>Price</th>
          <th>Description</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      {% for f in products %}
      {% if f %}
      <tr style="background-color: aliceblue;">
        <td>{{f.name}}</td>
        <td><img style="height: 20px; width:auto;" src="{{f.product_image.url}}" alt=""></td>
        <td>{{f.price}}</td>
        <td>{{f.description}}</td>
        <td><a class="btn btn-primary btn-xs" href="{% url 'update-product' f.id  %}"><span class="glyphicon glyphicon-edit"> Update</span></a></td>
        <td><a class="btn btn-danger btn-xs" href="{% url 'delete-product' f.id  %}"><span class="glyphicon glyphicon-trash"> Delete</span></a></td>
      </tr>
      {% else %}
     

      <br><br><br>
      <h1>no products</h1>

      {% endif %}
      {% endfor %}
      
    </table>

    <!-- PAGINATION STARTS -->
    <nav aria-label="..." class="container pt-5">
      {% if products.has_other_pages %}
      <ul class="pagination">
          {% if products.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page={{ users.previous_page_number }}"><i
                      class="fas fa-angle-left"></i></a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link"><i class="fas fa-angle-left"></i></a>
          </li>
          {% endif %}

          {% for i in products.paginator.page_range %}
          {% if users.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}

          {% if products.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ users.next_page_number }}"><i
                      class="fas fa-angle-right"></i></a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link"><i class="fas fa-angle-right"></i></a>
          </li>
          {% endif %}
      </ul>
      {% endif %}
  </nav>
  <!-- PAGINATION ENDS -->
  </div>
</div>
<!-- add product floating button -->
<a href="/addproduct" class="float">
<i class="fa fa-plus my-float"></i>
</a>


{% endblock content %}

Flower/templates/adminControl/admin_update_product.html
{% extends 'admin_base.html' %}

{% block content %}


{% load static %}


<head>
  <style media="screen">
    a:link {
      text-decoration: none;
    }

    .note {
      text-align: center;
      height: 80px;
      background: -webkit-linear-gradient(left, #0072ff, #8811c5);
      color: #fff;
      font-weight: bold;
      line-height: 80px;
    }

    .form-content {
      padding: 5%;
      border: 1px solid #ced4da;
      margin-bottom: 2%;
    }

    .form-control {
      border-radius: 1.5rem;
    }

    .btnSubmit {
      border: none;
      border-radius: 1.5rem;
      padding: 1%;
      width: 20%;
      cursor: pointer;
      background: #0062cc;
      color: #fff;
    }

    .menu {
      top: 50px;
    }
  </style>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<br><br><br><br><br><br>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container register-form">
    <div class="form"> 
      <div class="note">
        <p>Update Products</p>
      </div>
      <div class="form-content">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="col-md-4 control-label" for="">PRODUCT NAME</label>
              <div class="col-md-12">
                <input name="name" value="{{products.name}}" class="form-control input-md" required="" type="text">

              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="">PRODUCT Price</label>
              <div class="col-md-12">
                <input name="price" value="{{products.price}}"  placeholder="" class="form-control input-md" required="" type="number">

              </div>
            </div>

          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <label for="id_product_image">Product image:</label>
            <div class="col-md-4">
              <input type="file" name="product_image" accept="image/*" id="id_product_image">

            </div>
          </div>

        </div>
        <div class="form-group">
          <label class="col-md-4 control-label" for="">PRODUCT Description</label>
          <div class="col-md-12">

            <input name="description" value="{{products.description}}"  class="form-control input-md" required=""
              type="text"> 

          </div>

        </div>
      </div>
    </div>
    <button type="submit" class="btnSubmit">Update</button>
  </div>
  </div>
  </div>
</form>

{% endblock %}

Flower/templates/adminControl/admindashboard.html
{% extends 'admin_base.html' %}

{% block content %}

{% load static %}




<div class="container-fluid">
  <div class="row">

    <div class="card col-lg-4 col-md-4 col-12" style="background-color: aliceblue;">
      <img src="" class="card-img-top" alt="">
      <div class="card-body">
        <h5 class="card-title">Total customer</h5>
        <p class="card-text">{{usercount}}</p>
        <a href="view-customer" class="btn btn-primary " style="background-color: pink;">Customer List</a>
      </div>
    </div>
    <div class="card col-xs-6 col-sm-3" style="background-color: aliceblue;">
      <img src="" class="card-img-top" alt="">
      <div class="card-body">
        <h5 class="card-title"> Total Product</h5>
        <p class="card-text">{{productcount}}</p>
        <a href="admin-products" class="btn btn-primary"  style="background-color: pink;" >Product List</a>
      </div>
    </div>
    <div class="card col-lg-4 col-md-4 col-12" style="background-color: aliceblue;">
      <img src="" class="card-img-top" alt="">
      <div class="card-body">
        <h5 class="card-title">Total Booking</h5>
        <p class="card-text">{{bookcount}}</p>
        <a href="admin-view-booking" class="btn btn-primary"  style="background-color: pink;">Booking list</a>
      </div>
    </div>


  </div>
</div>








<!-- 
<section>
    <body>
        <div class="market-updates">
          <div class="col-md-4 market-update-gd">
            <div class="market-update-block clr-block-1">
              <div class="col-md-8 market-update-left">
                <h3>{{usercount}}</h3>
                <h4>Total Customer</h4>
      
              </div>
              <div class="col-md-4 market-update-right">
                <i class="fa fa-user-o"></i>
              </div>
              <div class="clearfix"> </div>
            </div>
          </div>
          <div class="col-md-4 market-update-gd">
            <div class="market-update-block clr-block-2">
              <div class="col-md-8 market-update-left">
                <h3>{{productcount}}</h3>
                <h4>Total Product</h4>
      
              </div>
              <div class="col-md-4 market-update-right">
                <i class="fa fa-shopping-basket"></i>
              </div>
              <div class="clearfix"> </div>
            </div>
          </div>
          <div class="col-md-4 market-update-gd">
            <div class="market-update-block clr-block-3">
              <div class="col-md-8 market-update-left">
                
                <h4>Total Orders</h4>
      
              </div>
              <div class="col-md-4 market-update-right">
                <i class="fa fa-bar-chart"> </i>
              </div>
              <div class="clearfix"> </div>
            </div>
          </div>
      
        </div>
        <br><br>
      </body>
</section> -->

{% endblock %}

Flower/templates/adminControl/adminlogin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<style>
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: poppins;
    }

    body {
        background-color: #E8EDF2;
    }

    div.container {
        position: absolute;
        top: 30%;
        left: 20%;
        transform: translate(-50% -50%);

        display: flex;
        flex-direction: row;

        align-items: center;
        background-color: white;
        padding: 30px;

    }

    div.container div.myform {
        width: 270px;
        margin-right: 30px;
    }

    div.container div.myform h2 {
        color: #1c1c1e;
        margin-bottom: 20px;
    }

    div.container div.myform input {
        border: none;
        outline: none;
        border-radius: 0;
        width: 100%;
        border-bottom: 2px solid #1c1c1e;
        margin-bottom: 25px;
        padding: 7px 0;
    }

    div.container div.myform button {
        color: white;
        background-color: antiquewhite;
        border: none;
        outline: none;
        border-radius: 2px;
        font-size: 14px;
        padding: 5px 12px;
        font-weight: 500;

    }



    @media(max-width:991px) {

        div.container {
            position: relative;
            left: 10%;
            width: 70%;
            margin-top: 30%;
        }

        div.container div.myform input {
            font-size: 20px;
        }

    }

    @media(max-width:450px) {

        div.container div.image img {
            width: 100px;
            font-size: 10px;

        }

        div.container div.myform input {
            font-size: 10px;
        }



    }
</style>

<body>
    <div class="container">
        <div class="myform">
            <form action="" method="POST">
                {% csrf_token %}
                <h2>ADMIN LOGIN</h2>
                <input type="text" name="username" placeholder="Username">
                <input type="password" name="password" placeholder="Password">
                <button type="submit">LOGIN</button>
            </form>
        </div>
        <div class="image">
            <img src="/static/Images/img-2.jpg" width="300px">
        </div>
    </div>
</body>

</html>

Flower/templates/adminControl/allblogs.html
{% extends 'admin_base.html' %}
{% load static %}
{% block content %}


<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }

    .float{
	position:fixed;
	width:70px;
	height:70px;
	bottom:60px;
	right:60px;
	background-color:red;
	color:#FFF;
	border-radius:50px;
	text-align:center;
	box-shadow: 3px 3px 3px #999;
}

.my-float{
	margin-top:22px;
}
  </style>
</head>


<div class="container">
  <div class=""  style="background-color: azure;">
    <div class="panel-heading">
      <h6 class="panel-title">Total Blog List</h6>
    </div>
    <table class="table table-hover" id="dev-table">
      <thead>
        <tr  style="background-color: paleturquoise;">
          <th>Blog Title</th>
          <th> Blog Image</th>
          
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      {% for bg in blogs %}
      {% if bg %}
      <tr style="background-color: aliceblue;">
        <td>{{ bg.blog_name }}</td>
        <td><img style="height: 50px; width: auto;" src="{{ bg.blog_image.url }}" alt=""></td>
        <td><a class="btn btn-danger btn-xs" href="{% url 'update-blog' bg.blog_id  %}"><span class="glyphicon glyphicon-edit"> Update</span></a></td>
        <td><a class="btn btn-danger btn-xs" href="{% url 'delete-blogs' bg.blog_id  %}"><span class="glyphicon glyphicon-trash"> Delete</span></a></td>
      </tr>
      {% else %}
     

      <!-- <br><br><br>
      <h1>no products</h1> -->

      {% endif %}
      {% endfor %}
      
    </table>

    <!-- PAGINATION STARTS -->
    <nav aria-label="..." class="container pt-5">
      {% if blogs.has_other_pages %}
      <ul class="pagination">
          {% if blogs.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page={{ users.previous_page_number }}"><i
                      class="fas fa-angle-left"></i></a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link"><i class="fas fa-angle-left"></i></a>
          </li>
          {% endif %}

          {% for i in blogs.paginator.page_range %}
          {% if users.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}

          {% if blogs.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ users.next_page_number }}"><i
                      class="fas fa-angle-right"></i></a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link"><i class="fas fa-angle-right"></i></a>
          </li>
          {% endif %}
      </ul>
      {% endif %}
  </nav>
  <!-- PAGINATION ENDS -->
  </div>
</div>
<!-- add product floating button -->
<a href="/blogform" class="float">
<i class="fa fa-plus my-float"></i>
</a>


{% endblock content %}

Flower/templates/adminControl/booking.html
{% extends 'admin_base.html' %}
{% load static %}
{% block content %}


<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  
<style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }

    .float{
	position:fixed;
	width:70px;
	height:70px;
	bottom:60px;
	right:60px;
	background-color:red;
	color:#FFF;
	border-radius:50px;
	text-align:center;
	box-shadow: 3px 3px 3px #999;
}

.my-float{
	margin-top:22px;
}
  </style>

<div class="container">
    <div class=""  style="background-color: azure;" >
      <div class="panel-heading">
        <h6 class="panel-title">Total Customer List</h6>
      </div>
      <table class="table table-hover" id="dev-table">
        <thead>
            <tr style="background-color: paleturquoise;">
                <th>Customer Name</th>
                    <th>Email</th>
                    <th>Product Name</th>
                    <th>Image</th>
                    <th>Price</th>
                    <th>Status</th>
                    <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for od in order %}
            <tr style="background-color: aliceblue;">
                <td>{{ od.user.first_name }} {{ od.user.last_name }}</td>
                <td>{{ od.user.email }}</td>
                <td>{{ od.product.name }}</td>
                <td> <img src="{{ od.product.product_image.url }}" alt="Profile Pic" height="30px" width="40px" />
                </td>
                <td>{{ od.product.price }}</td>
                <td>{{ od.status }}</td>
                <td><a class="btn btn-danger btn-xs" href="{% url 'delete-order' od.id  %}"><span
                            class="glyphicon glyphicon-trash">DELETE</span></a></td>
            </tr>
            {% endfor %}

        </tbody>
      
    </table>
    <!-- PAGINATION STARTS -->
    <nav aria-label="..." class="container pt-5">
        {% if order.has_other_pages %}
        <ul class="pagination">
            {% if order.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ order.previous_page_number }}"><i class="fas fa-angle-left"></i></a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link"><i class="fas fa-angle-left"></i></a>
            </li>
            {% endif %}

            {% for i in order.paginator.page_range %}
            {% if order.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if order.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ order.next_page_number }}"><i class="fas fa-angle-right"></i></a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link"><i class="fas fa-angle-right"></i></a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </nav>
    <!-- PAGINATION ENDS -->
</div>

{% endblock content %}

Flower/templates/adminControl/view_customer.html
{% extends 'admin_base.html' %}
{% load static %}
{% block content %}


<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  
<style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }

    .float{
	position:fixed;
	width:70px;
	height:70px;
	bottom:60px;
	right:60px;
	background-color:red;
	color:#FFF;
	border-radius:50px;
	text-align:center;
	box-shadow: 3px 3px 3px #999;
}

.my-float{
	margin-top:22px;
}
  </style>

<div class="container">
    <div class="" style="background-color: azure;">
      <div class="panel-heading">
        <h6 class="panel-title">Total Customer List</h6>
      </div>
      <table class="table table-hover" id="dev-table">
        <thead>
            <tr style="background-color: paleturquoise;">
                <th>User Name</th>
                <th>Email</th>
               
            </tr>
        </thead>
        {% for c in users %}
        <tr style="background-color: aliceblue;">
            <td> {{c.username}}</td>
            <td>{{c.email}}</td>
        
           

        </tr>
      
    </table>
    {% endfor %}
   


<!-- PAGINATION STARTS -->
    <nav aria-label="..." class="container pt-5">
        {% if users.has_other_pages %}
        <ul class="pagination">
            {% if users.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ users.previous_page_number }}"><i
                        class="fas fa-angle-left"></i></a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link"><i class="fas fa-angle-left"></i></a>
            </li>
            {% endif %}

            {% for i in users.paginator.page_range %}
            {% if users.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if users.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ users.next_page_number }}"><i
                        class="fas fa-angle-right"></i></a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link"><i class="fas fa-angle-right"></i></a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </nav>
    <!-- PAGINATION ENDS -->

</div>
{% endblock content %}

Flower/templates/adminControl/viewbooking.html
{% extends 'admin_base.html' %}

{% block content %}

{% load static %}

<section style="margin-top: 200px;">
    <h1 style="color:#ccdbfd">Booked Items</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>price</th>
                <th>Image</th>
                <th>Description</th>
                <th>Location</th>
            </tr>
        </thead>
        <tbody>
            {%for od in order%}
            <tr>
                
                <td>{{od.your_name}}</td>
                <td>{{od.address}}</td>
                <td>{{od.date}}</td>
                <td>{{od.phone_number}}</td>
                <td>{{od.location}}</td>
                
            </tr>
            {%endfor%}
        </tbody>
    </table>
</section>

{% endblock %}